# Generated by Django 4.2.9 on 2025-04-14 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book', models.FileField(upload_to='book/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='course_month',
            field=models.IntegerField(blank=True, choices=[(0, '1 Oy'), (1, '3 Oy'), (2, '6 Oy'), (3, '12 Oy')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Block', 'Block')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Kokrakvatriceps', "Ko'krak va triceps"), ('QanotmashqlarivaBiceps', 'Qanot mashqlari va Biceps'), ('Qanotmashqlari', 'Qanot mashqlari'), ('Yelkamashqlari', 'Yelka mashqlari'), ('Oyoqmashqlari', 'Oyoq mashqlari'), ('Uysharoitidamashqlar(Erkaklaruchun)', 'Uy sharoitida mashqlar (Erkaklar uchun)'), ('Uysharoitidamashqlar(Ayollaruchun)', 'Uy sharoitida mashqlar (Ayollar uchun)'), ('Kardiovajismoniymashqlar', 'Kardio va jismoniy mashqlar'), ('Pressmashqlari', 'Press mashqlari'), ('Dietavatogriovqatlanish:ErkeklarvaAyollaruchun', "Dieta va to'g'ri ovqatlanish: Erkeklar va Ayollar uchun"), ('Sportqoshimchalari', "Sport qo'shimchalari"), ('Farmakalogiya(Ximiya)', 'Farmakalogiya (Ximiya)')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default=1, max_length=555),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number. Format should be +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
