# Generated by Django 4.2.9 on 2025-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_news_user_course_month_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
